### PR TITLE
Updated setup.py

### PR DESCRIPTION
**Pull request by teto**
setuptools prepends sys.prefix by default so no need to add it

To install in develop mode, you can do:
$ python3 setup.py develop --user (--uninstall to remove)
$ sudo python3 setup.py install_data (else paperwork won't find the resources)

Could you try installing on a paperwork-free system the previous install to see if it works ?

### CODE REVIEW

**Comment by jflesch** [comment]
Tested on a fresh Debian stable + KDE VM:

```
ERROR  paperwork.frontend.util        Can't find resource file 'mainwindow/appmenu.xml'. Aborting
INFO   paperwork.paperwork            Good bye
ERROR  paperwork.frontend.diag        === UNCATCHED EXCEPTION ===
Traceback (most recent call last):
  File "/usr/local/bin/paperwork", line 9, in <module>
    load_entry_point('paperwork==1.2', 'gui_scripts', 'paperwork')()
  File "/usr/local/lib/python3.4/dist-packages/paperwork-1.2-py3.4.egg/paperwork/paperwork.py", line 144, in main
    main_win = MainWindow(config)
  File "/usr/local/lib/python3.4/dist-packages/paperwork-1.2-py3.4.egg/paperwork/frontend/mainwindow/__init__.py", line 2341, in __init__
    self.__advanced_app_menu = self.__init_app_menu(config, self.app)
  File "/usr/local/lib/python3.4/dist-packages/paperwork-1.2-py3.4.egg/paperwork/frontend/mainwindow/__init__.py", line 2911, in __init_app_menu
    app_menu = load_uifile(os.path.join("mainwindow", "appmenu.xml"))
  File "/usr/local/lib/python3.4/dist-packages/paperwork-1.2-py3.4.egg/paperwork/frontend/util/__init__.py", line 145, in load_uifile
    raise Exception("Can't find resource file '%s'. Aborting" % filename)
Exception: Can't find resource file 'mainwindow/appmenu.xml'. Aborting
ERROR  paperwork.frontend.diag        ===========================
```

**Comment by jflesch** [comment]
ping ?

**Comment by teto** [comment]
I plan to work on this next time I use paperwork. This might be weeks or months, hope that's ok with you.
Do you plan to setup some CI ? Travis.ci is easy to setup (~20 mn) & free. That could help with testing simple things like installation of the package.

**Comment by jflesch** [comment]
No problem. Take your time.
Regarding CI, I was thinking more about packaging automatically things than testing. Because testing requires starting Paperwork, which is a Gtk GUI ... no sure it's doable (easily anyway).

**Comment by teto** [comment]
it seems doable https://docs.travis-ci.com/user/gui-and-headless-browsers/

**Comment by teto** [comment]
`python3 setup.py develop --user` seems to work on unstable (notwistanding a few issues with missing pictures ? if you confirm, you can close this.

Btw, would you be interested in an patch to provide some CLI flags (like log verbosity) ? I tried the usual `paperwork --version` and `paperwork --help` but it launches the gui which can be troublesome.

**Comment by teto** [comment]
unstable branch does not work (aka I can't click on the menu to print for instance) in develop mode still because of how the data is handled.

```
WARNING paperwork.frontend.util        Failed to preload 'mainwindow/paperwork_halo.svg' !

(paperwork:28744): Gtk-WARNING **: Could not load image 'paperwork_halo.svg': Impossible d'ouvrir le fichier « /home/teto/paperwork/src/paperwork/frontend/mainwindow/paperwork_halo.svg » : Aucun fichier ou dossier de ce type


(paperwork:28562): Gtk-WARNING **: Negative content width -10 (allocation 1, extents 5x6) while allocating gadget (node headerbar, owner GtkHeaderBar)
```

When looking at setup.py, some data is installed via data_files (i.e., in sys.prefix) but unused mostly while some is installed via package_data (https://packaging.python.org/tutorials/distributing-packages/#package-data / https://setuptools.readthedocs.io/en/latest/setuptools.html#including-data-files). The project uses both as it loads files with pgk_resources but also resorts to this kind of hack https://github.com/openpaperwork/paperwork/pull/614/files#diff-0e86c12cbceb60d8128f73b8f2c07746R46.
It's weird to have code (preload_file) that just checks if a file exists. It has an impact on performance too. I would like to know your opinion on this. Either we use a "public" location with data_file and load pictures from there or we use package data and load it through pkg_resource.

nb It seems like python is used to do some of the distrib-level tasks. For instance src/paperwork/frontend/shell.py would be best served with a proper paperwork.desktop and a makefile IMO. Either people can copy the .destkop or use the makefile, for instance:
`xdg-desktop-menu install --novendor paperwork.desktop`
`xdg-icon-resource install --novendor --size 128 paperwork.png`

**Comment by jflesch** [comment]
> When looking at setup.py, some data is installed via data_files

Sorry, the branch 'unstable' wasn't up-to-date with the latest changes from 'stable'. I was too busy fixing some mess in the branch 'stable' and forgot to merge back in 'unstable' ... :/

**Comment by jflesch** [comment]
Unstable branch is up-to-date now

**Pull request closed without merging**
